name: tests

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: set up env
      run: cp .env.default .env
    - name: docker-compose pull
      run: docker-compose pull
    - uses: satackey/action-docker-layer-caching@v0.0.11
    - name: docker-compose build
      run: docker-compose build --build-arg UID="$UID"
    - name: docker-compose up services
      run: docker-compose up -d db redis
    - name: Test
      run: |
        docker-compose run service pybabel compile -d locale
        docker-compose run service coverage run ./manage.py test
        docker-compose run service coverage report
        docker-compose run service coverage xml
    - name: Send coverage to Codacy
      env:
          CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}
      run: |
        pip install codacy-coverage==1.3.11
        python-codacy-coverage -r ./coverage.xml
